version: 2
updates:
  - package-ecosystem: "pip"
    assignees:
      - swimmwatch
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"
    labels:
      - "pip"
      - "dependencies"

  - package-ecosystem: "github-actions"
    assignees:
      - swimmwatch
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
