name: "Release and deploy package to PyPI"

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and deploy to PyPI"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pypi
    strategy:
      matrix:
        poetry-version: ["1.8.5"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Install Poetry ${{matrix.poetry-version}}"
        run: pipx install poetry==${{matrix.poetry-version}}
      - name: "Setup Python"
        uses: actions/setup-python@v5
      - name: "Build package"
        run: poetry build
      - name: "Publish package distributions to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/